title: Henrieke Baunack # your name (or website title) here
logo: "/images/round_me2.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I recently graduated from UC Berkeley with a Masters degree. 
  I am now looking for my next adventure that preferably would be a job or internship in the field of data visualization and/or machine learning.
  <br><br>
  
  <h2> Latest Updates </h2>
  
  <p> 6/17/2020: Added this week's #makeovermonday submission. Check out <a href="https://henny2.github.io/portfolio/makeovermonday">my design</a> about high school sports in the US. </p>
  
  <br><br>
  
  <div style ="margin-left: auto;
  margin-right: auto;">
  <a href='https://www.linkedin.com/in/henrieke-baunack'>
  <img src="images/linkedin.png?raw=true" width="30" height="30">
  </a>
  
  <a href='https://www.instagram.com/henny2.0/?hl=en'>
  <img src="images/instagram.png?raw=true" width="30" height="30">
  </a>

  <a href='https://github.com/Henny2'>
  <img src="images/github.png?raw=true" width="30" height="30">
  </a>
  </div>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
